export LANG=en_US.UTF-8
export EDITOR='nvim'
export PATH=$HOME/bin:$HOME/.local/bin:/usr/local/bin:$PATH
export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="spaceship"
CASE_SENSITIVE="true"
plugins=(git)

zstyle ':omz:update' mode reminder
source $ZSH/oh-my-zsh.sh

# Aliases
alias vim='nvim'
alias backup='rsync -ahv --info=progress2 --no-i-r --partial'

# Spaceship Settings
SPACESHIP_PROMPT_ORDER=(
  time          # Time stamps
  dir           # Current directory
  git           # Git branch
  exec_time     # Execution time
  rust
  line_sep      # Line break
  jobs          # Background jobs indicator
  user          # Username section
  host          # Hostname section
  exit_code     # Exit code section
  char          # Prompt character
)

# User and Hostname Config
SPACESHIP_HOST_SHOW="always"
SPACESHIP_HOST_PREFIX="@"
SPACESHIP_USER_PREFIX=""
SPACESHIP_USER_SUFFIX=""
SPACESHIP_USER_SHOW="always"

# Date and Time Config
SPACESHIP_TIME_SHOW=true
SPACESHIP_TIME_FORMAT='%D{%H:%M:%S.%.}'

# Unknown
SPACESHIP_DIR_TRUNC=0
SPACESHIP_DIR_TRUNC_REPO=false

# Git
SPACESHIP_GIT_ORDER=(git_branch git_commit git_status)
SPACESHIP_GIT_COMMIT_SHOW=true
SPACESHIP_GIT_COMMIT_PREFIX=" at "

# Rust Spaceship Config
SPACESHIP_RUST_SHOW=true

# Source Cargo Directory
source $HOME/.cargo/env

# Launch or attach to a Tmux session by default if not already in TMUX
# if command -v tmux &> /dev/null && [ -n "$PS1" ] && [[ ! "$TERM" =~ screen ]] && [[ ! "$TERM" =~ tmux ]] && [ -z "$TMUX" ]; then
#     # Try to attach to an existing tmux session; if none, create a new one
#     tmux attach || exec tmux
# fi
